#!/bin/bash
##
# Copyright 2018 Pixelworks Inc.
#
# Author: Cheng Chi <cchi@pixelworks.com>
#
# All exported commands in function style here
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#               http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
## // ##


[ "$1" == '' ] && exit 0

ADTOOL=/usr/local/bin/adtool

OUTPUT=`$ADTOOL search samaccountname $1`

[ "$OUTPUT" == '' ] && echo "用户找不到 username not found" && exit 0

USER=$(echo $OUTPUT |cut -f 1 -d","|cut -f 2 -d "=")

LOCK=$($ADTOOL attributeget "$USER" lockoutTime)

[ "$LOCK" == "0" ] && echo "账户没有锁 account not locked" && exit 0
echo "账号已经解锁 account get unlock"
$ADTOOL attributereplace "$USER" lockoutTime 0

exit 0
